use_frameworks!

platform :ios, '8.0'

target 'GMSandboxTool_Example' do
  pod 'GMSandboxTool', :path => '../'

  target 'GMSandboxTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
